# Generated by Django 2.0.4 on 2018-04-10 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OnmyojiSearch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaptermonster',
            name='monster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnmyojiSearch.Monster'),
        ),
        migrations.AlterField(
            model_name='chaptermonsterdetail',
            name='monster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnmyojiSearch.Monster'),
        ),
    ]
