# Generated by Django 2.0.4 on 2018-04-10 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnmyojiSearch', '0002_auto_20180410_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaptermonsterdetail',
            name='monster',
            field=models.CharField(max_length=20),
        ),
    ]
